I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/softaredev_room.rpy", line 301, in script
    show jorrit angry at f2
  File "game/softaredev_room.rpy", line 301, in <module>
    show jorrit angry at f2
NameError: name 'f2' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/softaredev_room.rpy", line 301, in script
    show jorrit angry at f2
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1367, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 1367, in <listcomp>
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/softaredev_room.rpy", line 301, in <module>
    show jorrit angry at f2
NameError: name 'f2' is not defined

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Project Play 0.1
Wed Dec 21 11:58:10 2022
